// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfvvwhieanuwhrygvjjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdnZ3aGllYW51d2hyeWd2ampyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTY4NDcsImV4cCI6MjA2ODc3Mjg0N30.P3crMSQIYvWeGQHk4Nozg-5EWqyLfi8v_0ZFDFnpi6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});